### ISSUE TITLE
Using gitpod with this repo complains about zsh

### ISSUE THREAD

**Issue by juandemanjon** [numine777/OffByOne#1]
If you try to open this repo with Gitpod [https://gitpod.io/#https://github.com/numine777/OffByOne](url) flake.nix complains about missing zsh

After changing flake.nix to use bash ```runScript = "bash";``` it complains about missing shared symbol

```
direnv: loading /workspace/OffByOne/.envrc
direnv: using flake
warning: Git tree '/workspace/OffByOne' is dirty
bash: ps: command not found
direnv: loading /workspace/OffByOne/.envrc
direnv: using flake
nix: symbol lookup error: /usr/lib/libc.so.6: undefined symbol: __nptl_change_stack_perm, version GLIBC_PRIVATE
bash: __git_ps1: command not found
```

**Comment by numine777** [comment]
Interesting.  I had a separate issue running this on NixOS, so I've removed the shellHook.  For now, if you'd like to go to zsh after dropping into the nix shell, simply run zsh and it should work.  About to try this on Ubuntu 16.04 to verify that it's not broken on other OSes.

**Comment by numine777** [comment]
Actually, since this sets up it's own FHS environment, you won't have access to zsh unless you add it to the shell packages.  But this should work well now (verified that it works on my work machine without additional configuration after the changes I made).

**Comment by juandemanjon** [comment]
Thank you for the fix!

I confirm that I am able to build and I got:

```
Target //:OffByOne up-to-date:
  bazel-bin/OffByOne_/OffByOne
INFO: Elapsed time: 51.178s, Critical Path: 11.38s
INFO: 42 processes: 4 internal, 38 linux-sandbox.
INFO: Build completed successfully, 42 total actions
INFO: Build completed successfully, 42 total actions
```
```
Successfully setup running on port 6969!
Endpoint Hit: homePage
```

But when I run direnv, gitpod container still complains

```bash
direnv allow
```
```
direnv: loading /workspace/OffByOne/.envrc
direnv: using flake
nix: symbol lookup error: /usr/lib/libc.so.6: undefined symbol: __nptl_change_stack_perm, version GLIBC_PRIVATE
bash: __git_ps1: command not found
```

**Comment by numine777** [comment]
No problem!  That is strange.  My guess is that it may have something to do with the way that nix is installed on the gitpod instance.  Also very interesting that gitpod is offering nix integration now!  I've never tried using them together
